name: 'Generic Composer Updater'
description: 'A reusable action to update composer dependencies and create a pull request with dynamic versioning.'
inputs:
  package-name:
    description: 'The name of the main package to use for versioning the PR (e.g., "typo3/cms-core").'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get PHP version from composer.json
      id: get_php_version
      shell: bash
      run: echo "PHP_VERSION=$(jq -r '.config.platform.php' composer.json)" >> $GITHUB_ENV
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
    - name: Update composer
      shell: bash
      run: composer update --prefer-dist --no-interaction
    - name: Get Package Version
      id: get_version
      shell: bash
      run: echo "PACKAGE_VERSION=$(jq -r '.packages[] | select(.name=="${{ inputs.package-name }}") | .version' composer.lock)" >> $GITHUB_ENV
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'chore(deps): update ${{ inputs.package-name }} to ${{ env.PACKAGE_VERSION }}'
        title: 'Update ${{ inputs.package-name }} to ${{ env.PACKAGE_VERSION }}'
        body: 'This PR updates ${{ inputs.package-name }} and other composer dependencies.'
        branch: 'chore/update-${{ inputs.package-name }}-${{ env.PACKAGE_VERSION }}'
